# docker-compose.yml

version: '3.8'

services:
  # Serviço da Aplicação (Laravel/PHP)
  app:
    build:
      args:
        user: eduardo01 
        uid: 1000 
      context: .
    image: meu-projeto-laravel
    container_name: my-wallet-app
    restart: unless-stopped
    working_dir: /var/www/
    ports: 
      - "5173:5173"
    volumes:
      - ./:/var/www
    networks:
      - laravel-network

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: meu-projeto-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_FORWARD}:5432" # Expõe a porta para acesso externo (ex: DBeaver)
    networks:
      - laravel-network

  # Serviço do Servidor Web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: meu-projeto-nginx
    restart: unless-stopped
    ports:
      - "8000:80" 
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app
      - db

networks:
  laravel-network:
    driver: bridge

volumes:
  pgdata:
    driver: local