version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mywallet-php-dev
    container_name: mywallet-php-dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx:latest
    container_name: mywallet-nginx-dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  vite:
    image: node:20
    container_name: mywallet-vite-dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: mywallet-postgres-dev
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: