version: '3.8'

services:
  # Serviço da Aplicação mywallet
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: mywallet_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - postgres
    networks:
      - mywallet

  # Serviço do Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: mywallet_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      # AQUI ESTÁ A MUDANÇA: o caminho agora aponta para a pasta 'docker'
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/html:/var/www/html
      
    depends_on:
      - app
    networks:
      - mywallet

  # Serviço do Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: mywallet_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
    networks:
      - mywallet

networks:
  mywallet:
    driver: bridge

volumes:
  postgres-data:
    driver: local